# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58cbb5d254e88ae11695ab8c7c6a475303d3e29f7e0c38ed0817f83dac11c2a36041de16f2be3fe340836631713c8917e330d06579b1db6326645b5c751bb15f

test:
  secret_key_base: 2bbf834ab1209e2eb9aeb3aa3e0c677194d2e4eac1a55a604ae21787542330d93d64c1b95e323abb982e90c101a3ba9d8e1573a6e8c054e2c026b7dcdaf44755

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
